### ISSUE TITLE
Support TOML input

### ISSUE THREAD

**Issue by garethr** [instrumenta/conftest#1]
To expand the potential places where Conftest could be used, it would be good to support [TOML](https://github.com/toml-lang/toml) as an input. Conftest currently supports JSON or YAML only as input, but should work with any format we can unmarshall.

This should just be about either using something more generic, or adding some logic around the current use of the YAML module around [this line](https://github.com/instrumenta/conftest/blob/master/conftest.go#L145).

**Comment by Blokje5** [comment]
I would like to pick up this issue
