### ISSUE TITLE
Support for more authentication options when pulling/pushing Rego policies

### ISSUE THREAD

**Issue by Blokje5** [instrumenta/conftest#101]
ORAS supports basic http auth when pushing/pulling from a OCI registry and connecting to a registry without validating SSL. This can be useful when setting up a local docker registry running in a Kubernetes cluster in order to test a CI/CD pipeline running conftest. My suggestion is to add the `--username` and `--password` flags. Ideally also a `--insecure` flag to allow for skipping SSL validation.

**Comment by jpreese** [comment]
Closing due to #107
