### ISSUE TITLE
Support HTTP/HTTPS/Git for fetching policies.

### ISSUE THREAD

**Issue by Blokje5** [instrumenta/conftest#102]
A comment in #98 had a good [use case for supporting HTTP/HTTPS for fetching policies](https://github.com/instrumenta/conftest/issues/98#issuecomment-538515667). It would be great to test out policies found on e.g. Github in order to quickly test them. 

I think we can at least support HTTP/HTTPS but others that would be nice include for example Git and S3 like blob storages.

**Comment by garethr** [comment]
Good idea. I think considering reuse generally, with support for multiple backends, would be great.

I'm also happy to break what we have today if needed if that results in a more consistent experience across backends.

**Comment by nicolasbernard** [comment]
https://github.com/hashicorp/go-getter is a Go library, already supporting http, S3 and Git, it can be a good start.

**Comment by Blokje5** [comment]
Yeah, might be a good starting point. I'll see if I can pick this up this week/weekend.

**Comment by Blokje5** [comment]
#107 Implements this. conftest now supports everything go-getter supports + ORAS for pulling policies.
