### ISSUE TITLE
Flags defined on all commands that are only relevant for certain commands

### ISSUE THREAD

**Issue by Blokje5** [instrumenta/conftest#112]
Some flags (i.e. `--trace` and `--namespace`. Also `--no-color` but I can imagine that being relevant for all commands at some point) are available on for all commands, but only relevant for some. They should be moved up to the relevant commands, so that users don't get confused when trying `conftest pull --trace`.

**Comment by menendezjaume** [comment]
Hey @Blokje5,
I'd love to contribute to the project. Am I OK to pick this up?
Also, just to confirm the scope of this, I've had a look at the code and I believe both `--trace` and `--namespace` are currently only being used by `test`. Is that correct? I'll move them there if so.
Do you want to move `--no-color` too or shall I leave it where it is? Thanks!

**Comment by jpreese** [comment]
Sounds good to me @menendezjaume! Sounds like you've already done some investigative work for which flags apply to which command, but you've got the scope correct. 

We should move the flags to their relevant commands as to not show flags that have no impact on other commands.

**Comment by Blokje5** [comment]
Closed thanks to @menendezjaume
