### ISSUE TITLE
Resolve golanglint-ci errors

### ISSUE THREAD

**Issue by jpreese** [instrumenta/conftest#116]
When working on #115, I noticed there's an error about an invalid json output, and we're not getting inline comments anymore.

Since it's a hook, it's most likely setup and configured behind conftest's settings.

@garethr

**Comment by boranx** [comment]
Is this still an issue for PRs? I saw the problem on the day you opened a PR, however, they look fine for now. (Maybe that was golanglint-ci's internal problem for that day)

**Comment by jpreese** [comment]
I'm honestly not sure. I'd have to commit a PR that causes golangci-lint to fail and see if it makes a comment.

**Comment by jpreese** [comment]
Problem does seem to be resolved. Will chalk it up as an issue with golangci-lint running on that day.
