### ISSUE TITLE
Provide additional feedback on conftest commands

### ISSUE THREAD

**Issue by jpreese** [instrumenta/conftest#141]
I think there's value in providing some additional feedback when running commands with `conftest`.

For example, running `./conftest verify` just returns an empty result. We don't know the path it attempted. Did it return nothing because it just returned an exit code 0 and the policies passed?

Maybe we could say "No policies found in [dir]", exit code 0, or something along those lines.

**Comment by boranx** [comment]
Fix is on the master. Closing this.
