### ISSUE TITLE
Move the output of `conftest test ... --trace` to output.go

### ISSUE THREAD

**Issue by menendezjaume** [instrumenta/conftest#167]
As suggested by @boranx in #163, and now that we have traces in the `verify` command using `output.go` and the `CheckResult` struct, It would be good to move the traces from the `test` command to use the same pattern.

**Comment by menendezjaume** [comment]
I can't assign it to myself, but I'll be working on this issue this week.

**Comment by jpreese** [comment]
Looking forward to it!

**Comment by boranx** [comment]
The fix is in master. Closing this, thanks @menendezjaume
