### ISSUE TITLE
Check if key exists in object in Rego

### ISSUE THREAD

**Issue by v-yzakapko** [instrumenta/conftest#170]
Hey all. I had a rule like this:
warn[msg] {
  manifests = input[filename]
  some i
  manifests[i].kind == "ServiceEntry" 
  **manifests[i].metadata.namespace != "external"**
  msg := sprintf("Error in %s. ServiceEntry %v, namespace should be external, but set %v",
  [filename, manifests[i].metadata.name, manifests[i].metadata.namespace])
}

But if the namespace field(bold string) is absent in manifest file, my policy does not work. I was trying to use the [has_key ](https://www.openpolicyagent.org/docs/latest/policy-cheatsheet/#%20merge-objects) function, but it does not work inside the rule. 

Manifest:

apiVersion: v1
kind: ServiceEntry 
metadata:
  name: test-serviceentry-tcp-invalid
spec:
  ports:
    - name: http
      port: 8080
      protocol: UDP
      targetPort: 8080

Running via: conftest test manifests/egress/manifest4-invalid.yaml -p policy/egress/egress_tcp_policy.rego --combine --trace

**Comment by KeisukeYamashita** [comment]
As far as I know, if the key dosn't exist it will be handled as undefined variable and the test will fail. This is a great thing because everything that your are trying to test should exist otherwise it is an invalid input.

I will investigate has_key function because I am also curious about that.

**Comment by jpreese** [comment]
Correct. I see this as more of a behavior of OPA itself, and less something that `conftest` should handle.

I experienced something similar. That thread and some additional context can be found here: https://github.com/open-policy-agent/opa/issues/1857
