### ISSUE TITLE
Consistent handling of errors and case-sensitive messages of the parser

### ISSUE THREAD

**Issue by menendezjaume** [instrumenta/conftest#171]
As a result of the review of #168, I've seen that the handling of errors and the case of the messages is not consistent across all the parsers.

With this issue, if it's OK with you, @boranx, I will be combining, where it makes sense, all err handling snippets of code from `parser/...` from:

```
err := ednParser.Unmarshal(test.controlConfigs, &unmarshalledConfigs)

if err != nil {
    t.Errorf("we should not have any errors on unmarshalling: %v", err)
}
```
to something like:
```
if err := ednParser.Unmarshal(test.controlConfigs, &unmarshalledConfigs); err != nil {
    t.Errorf("err on unmarshalling: %v", err)
}
```

A quick search has shown me that this mainly happens when calling `parser.Unmarshal(...)`, which has only two or three occurrences.

Also, I will be making all the error messages lowercase.

**Comment by jpreese** [comment]
Closed via #171 . Thanks @menendezjaume ! 🚀
