### ISSUE TITLE
Is there plans to support XML configs?

### ISSUE THREAD

**Issue by php-coder** [instrumenta/conftest#174]
Do you have plans to support configuration files in XML format?

**Comment by boranx** [comment]
Actually, that would be a good feature as we consider `xml` a `configuration language`.
For me, we should definitely support it. Are you willing to open a PR to add it?

**Comment by php-coder** [comment]
> Are you willing to open a PR to add it?

I'd expect that it's not so easy. I even don't know what library to use for work with XML in Golang.

**Comment by boranx** [comment]
If you wish, I can work on this.

**Comment by php-coder** [comment]
@boranx That would be great! I can help to test this.

**Comment by boranx** [comment]
@php-coder deal!. Gonna prepare a PR for this.
