### ISSUE TITLE
Output the line number where violation has occurred

### ISSUE THREAD

**Issue by php-coder** [instrumenta/conftest#177]
Given the example output:
``` console
$ conftest test deployment.yaml
FAIL - deployment.yaml - Containers must not run as root
```
It would be nice to also show a line where violation occurs. It helps to locate the place where to apply the fix faster.

(By the way, the example can be improved to also output the name of a container. This provides a better user experience.)

**Comment by php-coder** [comment]
@seedofpanic @besok JFYI

**Comment by garethr** [comment]
Unfortunately I don't think this is possible to solve generically? The example you provide would have a line number, but not all rego policies will do so - they may take inputs from multiple lines, or even multiple files.

It would be interesting to explore and see if a pattern exists for this in Rego itself. If one does then, with the incoming structured errors we might be able to support passing that to the UI as a first class citizen. 

Unless you have an idea of how to implement this I'm minded to close unfortunately.

**Comment by jpreese** [comment]
Agreed, I'm not sure this is possible given the current landscape. Going to close this out, but this is a great idea.
