### ISSUE TITLE
Moving some functions to package?

### ISSUE THREAD

**Issue by InTheCloudDan** [instrumenta/conftest#18]
Has there been any talk on moving some of the private functions like `buildCompile` to a separate package in the repo so they could be used as a library in other projects? Or would you have any interest in a PR that does this?

**Comment by garethr** [comment]
Hi @InTheCloudDan. I'd started out focused on getting a nice CLI interface. But it's definitely time to start splitting the single file up into packages and defining a useful public interface. I'd definitely be happy to see a PR for that. That then sets things up to have a proper test suite as well.

Did you have a particular usecase in mind for using conftest as a library?

**Comment by InTheCloudDan** [comment]
I'm looking to add these similar features to another cli. The same could be done with piping using conftest. But I think it's a nicer end user experience to have it all wrapped in one if possible. So in my case, you could call testing the policy with a flag like `--policy-check` and it would check a json/yaml object against the policy and if it passes then call the API with that data.

**Comment by garethr** [comment]
We've started moving things to packages in https://github.com/instrumenta/conftest/pull/30. Some conversation their about what the public interface might look like.
