### ISSUE TITLE
`test` should fail when using a non-existant namespace

### ISSUE THREAD

**Issue by jutley** [instrumenta/conftest#181]
I just caught an issue with some automated validation where we were using the `--namespace` flag, but the policy file was configured with a typo in its package. This means that none of the policies were being checked, but we had no idea.

I think that when `--namespace` is used, the command should fail if the namespace does not exist.

**Comment by KeisukeYamashita** [comment]
IMO, when there are no tests in that namespace, it should be treated as `success` because there are no polices. You will never fail unless there are no policies, this makes more sense.

**Comment by menendezjaume** [comment]
Agree with @KeisukeYamashita. No rules founds to me means that the test has been successful as there are no policies defined. Having said that, we could probably warn the users that no rules matching that namespace have been found.

**Comment by jutley** [comment]
I think a warning is probably appropriate. Ideally we can differentiate an incorrect namespace from the success case. A warning accomplishes this.

**Comment by jpreese** [comment]
I do agree that there should be some feedback. Even if that feed back is `0/0 policies passed`, exit code 0.

This would let the user know that no policies were checked, and could be expanded upon to count all succeeded policies when some are passed.

**Comment by jpreese** [comment]
This has been addressed in #254. When using a non-existant namespace, `conftest` will let you know that no policies were found.
