### ISSUE TITLE
Support output deny only mode

### ISSUE THREAD

**Issue by KeisukeYamashita** [instrumenta/conftest#190]
## What

* Currently `conftest` supports for 4 outputs
    * successes
    * failures
    * warnings
    * traces
* I suggest implementing a failure only mode like below.
    * With this flag enabled, it shows only `failures`.

```
$ conftest test config.yml -p policy.rego --failure-only
```

* The controversial part is, whether we should show `warnings` in `failure-only` mode.
* I can raise a PR for this.

## Why

* Admins will want to know the success too.
* But on the other hand, the most matter for developers will be failures for CI.

**Comment by boranx** [comment]
I'm curious that we need this flag really.

For the `traces`, the flag has been disabled by default, it can be turned on with `--trace`.
We have the `successes` option but it doesn't work for most of the parsers we support.
Like:
```shell
conftest test -p examples/ini/policy/deny.rego examples/ini/grafana.ini -o json # 5/6 of rules have passed.
conftest test -p examples/xml/policy/ examples/xml/pom.xml -o json  # 2/3 of rules have passed.
```

My gut tells me that we should pass `--verbose` flag(or something) if we want to see more verbose outputs like `passings` ( just like the other testing tools)

The `successes` and `traces` has to be disabled by default unless we pass `--verbose` nor `--trace`

**Comment by KeisukeYamashita** [comment]
@boranx  Currently, we don't support `successes` option. All verification and tests will output successes.

The latest master will output like below.

```
$ go run main.go test -p examples/kubernetes/policy examples/kubernetes/service.yaml                                                                                  
PASS - examples/kubernetes/service.yaml - data.main.deny
WARN - examples/kubernetes/service.yaml - Found service hello-kubernetes but services are not 
allowed
```

IMO, we should disable `PASS` which are policies that passed(=successes) by default and implement a `--verbose` (or something) flag to turn it on.

**Comment by boranx** [comment]
imho, it should be like this. However, I dunno what folks think about this.
@Blokje5 @jpreese what do you think about this?

**Comment by jpreese** [comment]
I'm not really seeing the value add. What is the problem that we're trying to solve?

I'm not completely against the idea, I think the behavior would be acceptable if by default conftest only rendered warnings and failures, and maybe only output a count of successes (e.g. 10/10 policies passed). But give the ability to show each passing policy via a `verbose` flag. This is the behavior of `go test`.

**Comment by KeisukeYamashita** [comment]
The `--failure-only`  can be `--deny-only` or something else.

The use case about `--failure-only` flag is showing output of failure policy only. 
Somethings we want `success, warning, deny(violations)` or only `deny(violations)`. 
In CI/CD, users don't want success output.

```
$ conftest test -p examples/kubernetes/policy examples/kubernetes/service.yaml -o table
+---------+----------------------------------+--------------------------------+
| RESULT  |               FILE               |            MESSAGE             |
+---------+----------------------------------+--------------------------------+
| success | examples/kubernetes/service.yaml |                                |
| warning | examples/kubernetes/service.yaml | Found service hello-kubernetes |
|         |                                  | but services are not allowed   |
+---------+----------------------------------+--------------------------------+
```

With the flag it shows only `failures`

$ conftest test -p examples/kubernetes/policy examples/kubernetes/service.yaml -o table --failure-only
+---------+----------------------------------+--------------------------------+
| RESULT  |               FILE               |            MESSAGE             |
+---------+----------------------------------+--------------------------------+
| failure | examples/kubernetes/service.yaml | Found service hello-kubernetes |
|         |                                  | but services are not allowed   |
+---------+----------------------------------+--------------------------------+

**Comment by jpreese** [comment]
I'm personally still in the camp of always showing successes. 

I could see us mimicing `go test` behavior where we pass/fail based on folders or namespaces, rather than every single policy, and adding a verbose flag that does essentially what we do now. This would reduce the number of lines from successes.

But with added commands brings added complexity, and a `--failure-only` flag just feels really niche to me. I get the idea of less text in CI, but then `--failure-only` becomes a CI-specific command which just doesn't sit right with me.

@boranx @Blokje5 @garethr

**Comment by kmcquade** [comment]
My 2 cents: This could be accomplished by piping the output and grepping the results. If it can be accomplished with a simple approach like that, I don’t think it necessarily requires adding a new flag.

**Comment by Blokje5** [comment]
I agree. A --failure-only flag is a bit niche, and will mostly complicate the codebase while the same could be achieved with a simple grep.

**Comment by garethr** [comment]
I'll close this as won't fix for now. It's a good discussion, but it seems the maintainers mainly agree that it's simple enough to handle outside of conftest where this is wanted.
