### ISSUE TITLE
ansible / yaml list input

### ISSUE THREAD

**Issue by kfox1111** [instrumenta/conftest#194]
Thinking about using conftest with ansible (its just yaml)

Its failing though. looks like input being a list doesn't quite behave properly. Not sure if this is a rego or a conftest issue.

Test file:
```
- name: foo
```

Test rego that should work but doesnt:
```
package main
deny[msg] {
  input[_].name == "foo"
  msg = "foo found"
}
```

**Comment by kfox1111** [comment]
It works in the rego sandbox, so it must be something conftest specific?

https://play.openpolicyagent.org/p/fayccvPEZx

**Comment by KeisukeYamashita** [comment]
It will work like this. `input` isn't a slice.

```
package main

deny[msg] {
  input.name == "foo"
  msg = "foo found"
}
```

**Comment by kfox1111** [comment]
so the top level list is stripped out by conftest?

Seems to work. Thanks.
