### ISSUE TITLE
Support EDN input

### ISSUE THREAD

**Issue by garethr** [instrumenta/conftest#2]
To expand the potential places where Conftest could be used, it would be good to support [EDN](https://github.com/edn-format/edn) as an input. Conftest currently supports JSON or YAML only as input, but should work with any format we can unmarshall.

This should just be about either using something more generic, or adding some logic around the current use of the YAML module around this line.

**Comment by garethr** [comment]
conftest now has a parser interface (see https://github.com/instrumenta/conftest/pull/17) which should support this feature.

**Comment by menendezjaume** [comment]
Would love to work on this if that's OK. I see that we could use [go-edn](https://github.com/go-edn/edn) and integrate it with the `util/parser.go` that @Blokje5 did.

**Comment by boranx** [comment]
support for `EDN` is now available.
