### ISSUE TITLE
Updates to parser.go break stdin functionality

### ISSUE THREAD

**Issue by nabadger** [instrumenta/conftest#20]
This used to work - looks like the code in question has been re-worked lately to check for file-extension types yaml/toml.

Given a valid yaml file `deploy.yaml` ...
```
cat deploy.yaml | conftest test - 
Unable to find available parser for extension 
```

Where as the following works fine
```
conftest test deploy.yaml 
```

**Comment by garethr** [comment]
Ah, thanks for flagging. I'll get a test added for this and get this fixed.

**Comment by boranx** [comment]
@garethr @Blokje5 The parser detects configuration with file suffixes, how can we detect the type if it comes from stdin?

**Comment by garethr** [comment]
I think the best approach here is to default to the YAML parser (which also handles JSON) and then to allow overriding with a flag. We could look at some format detection later maybe, but I think explicit is a good approach here. I'll take a run at this.

**Comment by garethr** [comment]
In the future using https://github.com/github/linguist/blob/master/lib/linguist/languages.yml would also be interesting. ie. detecting things like Cargo.lock as a TOML file.

**Comment by garethr** [comment]
I've pushed https://github.com/instrumenta/conftest/commit/5d14d0219f4a34e499de7ae22951dbc92e2f4438 which should resolve this. This also includes a test using stdin. Conftest 0.8.1 should be released shortly with the fix.
