### ISSUE TITLE
Automatically checking the input file

### ISSUE THREAD

**Issue by KeisukeYamashita** [instrumenta/conftest#200]
## What

Currently, we have `-i` flag for telling `conftest` what is the input file type is.

IMO, we can automatically get file type from the file extension.
I will like to raise a PR for this.

## Why

* Reduce flags. Making simple
* I can't find use cases where the file content is different from the file extension.

Currently, if we specify the wrong `-i`, it will return an error.

```
$ conftest test -p examples/kubernetes/policy examples/kubernetes/service.yaml -i hcl2
Error: get configurations: bulk unmarshal: parser unmarshal: parse hcl2 config: :1,1-11: Argument or block definition required; An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value., and 6 other diagno
stic(s)
Usage:
  conftest test <file> [file...] [flags]

Flags:
      --combine            combine all given config files to be evaluated together
      --fail-on-warn       return a non-zero exit code if only warnings are found
  -h, --help               help for test
  -i, --input string       input type for given source, especially useful when using conftest with stdin, valid options are: [toml tf|hcl cue ini yaml json edn xml]
      --namespace string   namespace in which to find deny and warn rules (default "main")
  -o, --output string      output format for conftest results - valid options are: [stdout json tap table]
      --trace              enable more verbose trace output for rego queries
  -u, --update strings     a list of urls can be provided to the update flag, which will download before the tests run

Global Flags:
      --no-color        disable color when printing
  -p, --policy string   path to the Rego policy files directory. For the test command, specifying a specific .rego file is allowed. (default "policy")

exit status 1
```

**Comment by davewongillies** [comment]
> I can't find use cases where the file content is different from the file extension.

The help mentions why it exists:

> especially useful when using conftest with stdin

So perhaps leave the flag there for stdin situations, but have the logic for figuring out the extension when an actual file has been provided for input?

Personally (and slightly unrelated) I think that flag should have been called `input-type` or something similar. Initially when I started using conftest I expected `--input` to specify the name of the input file.

**Comment by KeisukeYamashita** [comment]
I found out.
For Terraform file `.tf`, there are `hcl` and `hcl2`. That's the reason why this `-i` exists.

**Comment by KeisukeYamashita** [comment]
I will close cause I understand the reason why the `-i` flags exists. 
@davewongillies  Thank you very much :)
