### ISSUE TITLE
INI parse results will return all literals in string

### ISSUE THREAD

**Issue by KeisukeYamashita** [instrumenta/conftest#206]
## What

For non-string literals, the current INI parser will return it with string.

## How to reproduce

**Input sample INI**

```ini
[server]
# The http port to use
http_port = 3000
```

With policy like this will fail.

**Fail**

```rego
deny[msg] {
    not input.server.http_port = 3000
    msg = sprintf("Port should be %d", [port])
}
```

But it will success like below because the INI parser will return all literals in string.

**Success**

```rego
deny[msg] {
    not input.server.http_port = "3000"
    msg = sprintf("Port should be %d", [port])
}
```

IMO, we have two options to resolve this.

* Parse types correctly parser-level
    * Change the parser package, PR to the parser package ...
* Convert types using reflect package in instrumeta/conftest

Any thoughts?

**Comment by KeisukeYamashita** [comment]
Ah, this looks like a conftest problem...

INI supports int literal too, but in the conftest, it is converted as string

ref: https://ini.unknwon.io/docs/intro/getting_started

**Comment by KeisukeYamashita** [comment]
Raised a PR for this. Please take a look.

**Comment by garethr** [comment]
Fixed in # 211 which will be in the next release
