### ISSUE TITLE
Vars file flag

### ISSUE THREAD

**Issue by Salamandastron1** [instrumenta/conftest#230]
It'd be nice to have conftest populate rego code with a vars file or even data yaml files with a vars file. 

There are lot security scenarios where this would desirable as then configuration files could be committed to version control and then secretes kept secret

ala

```sh
$ conftest test kubernetes-pod.yml -l secretySecrets.yml
```

**Comment by boranx** [comment]
Is that what you mean?
https://github.com/instrumenta/conftest/blob/master/README.md#--data-flag

**Comment by garethr** [comment]
Data is now supported in master and will be in the next release. I think this resolves this usecase as well. I'll close this issue but please do re-open @Salamandastron1 if that's not the case.
