### ISSUE TITLE
Introduce --all-namespaces flag 

### ISSUE THREAD

**Issue by jpreese** [instrumenta/conftest#236]
### Current Behavior

The user must specify a `--namespace` in order to test policies in that package. If not specified, the `main` package is used.

### Proposal

Introduce a `--all-namespaces` flag, drawing inspiration from [Kubernetes flag of the same name](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources) that would open the `.rego`, grab the package from the top of the file, and use that for the namespace value.

**Comment by garethr** [comment]
I think this makes sense. I'd mainly being using namespaces to split policies for different types of files, but this is just as valid a usecase.

**Comment by jpreese** [comment]
Closed via #267. Thanks @menendezjaume 🎉
