### ISSUE TITLE
conftest passes a test that opa agent fails (it should fail)

### ISSUE THREAD

**Issue by chrisjohnson** [instrumenta/conftest#247]
a.rego
```
package main

# container name policies
any_invalid_container_name {
  services_with_valid_names := [ s | name := input.services[_].container_name
    name != null
    contains(name, "${HOSTNAME}")
    s := name ]

  count(services_with_valid_names) != count(input.services)
}
```

a_test.rego
```
package main

root = {
  "services": {"app": app_service}
}

app_service = {
  "container_name": "my-app-${HOSTNAME}",
  "image": "${IMAGE}:${TAG}",
  "ports": [app_port],
  "restart": "unless-stopped",
  "user": "deployer"
}

app_port = "${PORT}:3000"

test_any_invalid_container_name_with_invalid {
  any_invalid_container_name with input as root with input.services.app.container_name as null
}

test_any_invalid_container_name_with_invalid {
  any_invalid_container_name with input as root with input.services.app.container_name as "my-app-${HOSTNAME}"
}
```

Results of `conftest verify -p .`

```
PASS - a_test.rego - data.main.test_any_invalid_container_name_with_invalid
PASS - a_test.rego - data.main.test_any_invalid_container_name_with_invalid
```

Results of `opa test .`

```
data.main.test_any_invalid_container_name_with_invalid#01: FAIL (463.617µs)
--------------------------------------------------------------------------------
PASS: 1/2
FAIL: 1/2
```

This came up because I noticed the test wouldn't fail no matter what I did. I ran the same test in opa as a sanity check and opa behaves how I would expect.

Is this just something I'm doing wrong? What's the culprit?

It seems like removing the first test body makes it fail as expected. Is it because I'm referencing the same rule twice? How can I test a rule against multiple inputs to confirm that it produces the expected outputs?

**Comment by jpreese** [comment]
Thanks for submitting the issue @chrisjohnson.

First, to immediately resolve your issue, I would just rename the name of the test. You're using the same test name, `test_any_invalid_container_name_with_invalid`, in both cases.

You could change this to something like the following:

```rego
test_any_invalid_container_name_with_invalid {
  any_invalid_container_name with input as root with input.services.app.container_name as null
}

test_any_invalid_container_name_with_valid {
  any_invalid_container_name with input as root with input.services.app.container_name as "my-app-${HOSTNAME}"
}
```

In this case, you can uniquely name each test to express what you're trying to validate. Note that the same rule name is used in both cases.

Though it is worth noting that the behavior _is_ slightly different from `opa test`. I've opened PR #248 to address this.

**Comment by chrisjohnson** [comment]
I figured it was something I was doing wrong. Thanks very much for clarifying what I did and thanks as well for implementing a change to hopefully help others not make this same misstep :)
