### ISSUE TITLE
Make it possible to print successful tests regardless of output format

### ISSUE THREAD

**Issue by anderseknert** [instrumenta/conftest#258]
In a CI/CD context it is often valuable to have the result of all tests printed for inclusion in test reports. As I came to understand it only the JSON output format currently prints successful tests, but as we are using the TAP output format there is currently no way for us to have these tests included in the report with current tooling in place.

A command line option to include all tests would be a great addition.

**Comment by Blokje5** [comment]
After a short discussion in Slack, this is mostly for per rule success output. Right now conftest defaults to one success message per policy file. It should be possible to print a success for each rule evaluated. E.g. if a policy has 3 deny rules, there should be 3 lines of output instead of one. We can add a flag to enable/disable this behaviour.

**Comment by jpreese** [comment]
The case in which the rule names were the same would be my biggest question here. In the new output config, rules with the same name are deduped and a total# is given. I thought the other formats still printed out the redundant rule names, but I can take a look at each output.

**Comment by anderseknert** [comment]
Provided all the great input I got from you guys on Slack I retried my tests using differently named `deny_*` rules and they do indeed show up in the output even when not failing. So I'll happily close this one, leaving only a hope for this pattern matching on [deny|violation]* logic to be documented somewhere going forward. Thanks for a great tool and your excellent support on my case!

**Comment by jcmcken** [comment]
@anderseknert @Blokje5 Can you provide more information about how this is supposed to work?

I use rules named ``deny_*`` and I do not see any useful details about the successes. For example, in "table" format, the columns I see for successes are:

* ``RESULT``, with contents ``success``
* ``FILE``, with the file path of the config file under test
* ``NAMESPACE``, the exact string I pass to ``--namespace``
* ``MESSAGE``, statically set to ``SUCCESS``

The ``tap``, ``junit``, and ``json`` outputs (to pick some examples) have similar information.

**Comment by anderseknert** [comment]
@jcmcken not sure what you consider useful details here? All I wanted was for successful tests to be printed _at all_, which they seem to be in your example.

**Comment by jcmcken** [comment]
@anderseknert  Thanks, it wasn't clear exactly what you were expecting vs outcome.

For me, I'd like to treat each policy rule as a named test and output the tuple (``<name of test>``, ``<success|failure>``, ``<details>``, ``<test target>``) -- in some kind of serialized format ideally -- similar to unit testing tools in other programming languages.

For example, I have CI tooling that can ingest JUnit XML. ``conftest`` currently generates dummy ``testcase`` nodes in the resulting XML for successful test cases, making it impossible for the developer to explore the successes.

**Comment by anderseknert** [comment]
Ah, OK. What kind of `details´ would a successful test report? Logs?

**Comment by jcmcken** [comment]
``details`` would not be provided for a successful test, I'm just giving a general description. A successful test would just have the rule name ``deny_something_from_happening``. (I mean, if there's a way to give more metadata, that might be useful too).
