### ISSUE TITLE
Support directory as file input for test command

### ISSUE THREAD

**Issue by jpreese** [instrumenta/conftest#260]
## Current Behavior

A file, or list of files must be supplied to the `test` command

## Proposal

Allow `conftest` to figure out if the parameter is a directory, and if so, grab all of the files and execute your policies against them.

The only big question mark right now that I'd need to think through is figuring out which files to run validations against, and which ones to ignore as a directory can contain a whole bunch of different extensions.

**Comment by Blokje5** [comment]
What if we support file globs instead of supporting only searching directories? Then it becomes quite easy to ensure that only a certain type of file is tested.

**Comment by jpreese** [comment]
I'm actually working on this as we speak.

The only stumbling area I've had thus far is with hcl2 vs hcl.. so I want to test policies against all `.tf` files, but also whatever other files we support in that dir (maybe `Dockerfile`). But.. it fails because it's `hcl2`. But I can't pass in -i hcl2 because I want everything else.

So I think I'm just going to whip it up so that `conftest` figures out by itself if its hcl2 or hcl (try parsing both) and then if `-i` is passed, only grab those.
