### ISSUE TITLE
access environment variables

### ISSUE THREAD

**Issue by rosscdh** [instrumenta/conftest#274]
Hi there, thanks for the great project that helps catch governance issues at build time and not deploy time (saving sprints and developer tantrums).

Id like to access a os.env variable so that we can keep tests and make them relative to an environment

```
deny[msg] {
  env := ${ENVIRONMENT}
  not env = "dev"
  input.kind = "Service"
  input.metadata.name != "my-app-svc"
  input.spec.type = "NodePort"
  msg = sprintf("The Service[%s] in Env[%s] must not be a NodePort. The only NodePort should be the other-app-svc, the rest should be LoadBalancer or ClusterIp", [input.metadata.name, env])
}
```

is this supported/possible? or is there another way?

**Comment by rosscdh** [comment]
A La https://www.openpolicyagent.org/docs/latest/policy-reference/#opa

**Comment by dfonteps** [comment]
Hi @rosscdh, so you solved your problem by doing something like this?

env := opa.runtime().env.ENVIRONMENT
