### ISSUE TITLE
Broken documentation links to code examples

### ISSUE THREAD

**Issue by kmcquade** [instrumenta/conftest#277]
All the links on this page are broken.

https://www.conftest.dev/examples/

For example: 

https://www.conftest.dev/examples/examples/awssam

![image](https://user-images.githubusercontent.com/3422255/76331371-72a95200-62c5-11ea-9b4a-e683de8daead.png)

**Comment by garethr** [comment]
Fix for this in #282

**Comment by Blokje5** [comment]
Fixed by #282
