### ISSUE TITLE
Support HCL input

### ISSUE THREAD

**Issue by garethr** [instrumenta/conftest#3]
To expand the potential places where Conftest could be used, it would be good to support [HCL](https://www.terraform.io/docs/configuration/syntax.html) as used in Terraform and GitHub Actions as an input. Conftest currently supports JSON or YAML only as input, but should work with any format we can unmarshall.

This should just be about either using something more generic, or adding some logic around the current use of the YAML module around [this line](https://github.com/instrumenta/conftest/blob/master/conftest.go#L145).

**Comment by garethr** [comment]
conftest now has a parser interface (see https://github.com/instrumenta/conftest/pull/17) which should support this feature.

**Comment by Blokje5** [comment]
Is it the idea to support both HCL and HCL2?

**Comment by xchapter7x** [comment]
hey @garethr 
i sent over a PR which adds HCL support.
let me know your thoughts and feedback. thanks :)

https://github.com/instrumenta/conftest/pull/31

**Comment by garethr** [comment]
I've merged #31, thanks @xchapter7x.
