### ISSUE TITLE
Methods for ignoring kustomize patch files

### ISSUE THREAD

**Issue by ahume** [instrumenta/conftest#301]
Hi,

Sorry this isn't a bug or an issue as such. I'm curious what others are doing in the situation where there are kustomize patch files sitting alongside other full kubernetes manifests. The patch files look to conftest like kubernetes manifests (i.e. the have `apiVersion` and `kind` fields), but should not be validated as such.

Is anyone doing something more elegant than e.g. adding labels to the patch file to identify it, or naming them specially? Both of which pushes some effort up to developers creating the files which I'd rather avoid.

Thanks for any insight.

**Comment by garethr** [comment]
Hi @ahume. Probably a good question to ask in the #conftest Slack channel on https://slack.openpolicyagent.org/.

**Comment by ahume** [comment]
Hi @garethr - thanks, that's a better idea.
