### ISSUE TITLE
Support for json configs

### ISSUE THREAD

**Issue by rcshadman** [instrumenta/conftest#303]
Hi guys,
conftest is pretty cool, great work.
I just wondering if there is any support for handling  json config files. 
If it is not supported at the moment, it would be great to know if you are guys planning to implement a support for json files in future.
Cheers

**Comment by garethr** [comment]
Yes, JSON is supported as an input format. Technically YAML is a superset of JSON. This is also mentioned in the docs on https://www.conftest.dev/ in the list of supported formats.
