### ISSUE TITLE
Support CUE input

### ISSUE THREAD

**Issue by garethr** [instrumenta/conftest#4]
To expand the potential places where Conftest could be used, it would be good to support [CUE](https://cue.googlesource.com/cue/) natively as an input. Conftest currently supports JSON or YAML only as input, but should work with any format we can unmarshall.

We have [CUE examples](https://github.com/instrumenta/conftest/tree/master/examples/cue
), but would be useful to not require pipeline commands together.

This should just be about either using something more generic, or adding some logic around the current use of the YAML module around [this line](https://github.com/instrumenta/conftest/blob/master/conftest.go#L145).

**Comment by garethr** [comment]
conftest now has a parser interface (see https://github.com/instrumenta/conftest/pull/17) which should support this feature.

**Comment by boranx** [comment]
Hi @garethr, I would like to pick this issue if it's available. Currently, I'm preparing a PR that uses the current parser interface and native cue library :  [cuelang.org/go/cue](https://godoc.org/cuelang.org/go/cue)

**Comment by garethr** [comment]
Merged in #43
