### ISSUE TITLE
Adding additional maintainers to conftest

### ISSUE THREAD

**Issue by garethr** [instrumenta/conftest#41]
I've been super happy to see the interest in Conftest, both from folks wanting to use it and from several folks who have already contributed fixes and features. One of the reasons to start this under an org rather than my own name was to make it a touch easier to add other folks if the project proved interesting.

With that, I thought it would be easiest to open an issue to discuss.

Pinging @brendanjryan, @jpreesem, @Blokje5, @xchapter7x and @Proplex just in case that is something of interest?

**Comment by Proplex** [comment]
👋 heya, thanks for the ping

Just a little context as to why we're here: @xchapter7x, myself, and a few others are looking into using conftest as a way of TDDing our infrastructure deployments. Namely, that's Terraform (.tf), BOSH manifests (.yaml), and Pivotal Operations Manager manifests (.yaml). We think conftest has a lot of potential in solving our issues.

We've love to continue contributing to conftest, but I think we'd need a little more information/expectations from us around what being a `maintainer` would entail. Are y'all looking for a time commitment? What about opinions, roadmap, and contributions?

Thanks!

**Comment by Blokje5** [comment]
Yeah I have a similar reason to be here, we are utilising Terraform + Kubernetes to manage our infrastructure and we want to have a bit more control over what actually gets deployed. Conftest looked like a really good way to achieve it. 

I agree with @Proplex though. I would love to be a maintainer, but it is good to define what you are looking for in a maintainer.

**Comment by garethr** [comment]
My main reason for posting this was simply moving from "only I can merge things" to "a few people can merge things". So no real time expectations, mainly about avoiding bottlenecks and active contributors feeling some ownership over the project as well. I've messed this up previously and thought I'd be more proactive this time around.

I built Conftest because I wanted it to exist, and it's already better because others have contributed (yay OpenSource). I definitely think shared views on direction and features are useful, rather than any one person just calling all the shots.

I'm happy to have something to describe the role of maintainer in the context of this project, I know a number of projects have a MAINTAINERS file or similar. Would be good to find some examples actually of similar things.

**Comment by Blokje5** [comment]
Sounds good to me!

It might also be an idea to create a channel under the open-policy-agent slack, might be easier to discuss things there then to discuss on github issues. Especially when talking about the direction of the project and what to focus on that could simplify communications.

**Comment by jpreese** [comment]
Works for me! That's oddly convenient as I just sent you an email regarding this. I didn't see the initial ping because you've got an 'm' at the end of my name :)

**Comment by brendanjryan** [comment]
I'm very keen to discuss the roadmap / direction of this project as well! Perhaps we should do this before adding a lot of new maintainers to the project? 

> It might also be an idea to create a channel under the open-policy-agent slack

+1 to this!

I think being on the same page  makes a lot of sense before adding a lot of

**Comment by garethr** [comment]
I'll chat with the OPA folks about setting up a new channel. Will report back with details here and we can move the conversation.

**Comment by garethr** [comment]
I've asked the OPA folks and they said "no problem" to setting up a Slack channel.

You'll need to join the OPA Slack from https://slack.openpolicyagent.org/, and then you can access the channel at #conftest, https://openpolicyagent.slack.com/messages/CLE8VEKGT.

Any problems let me know.

**Comment by Proplex** [comment]
Thanks for the input earlier, @garethr. I'd love to help maintain the project along with everyone else and @xchapter7x, if you feel there's a need for more maintainers :) 

We've bene using conftest internally and would love to help it grow further.

**Comment by xchapter7x** [comment]
Hey @garethr ,

Thanks for the offer and apologies for the slow response.

I would be extremely interested in helping however I can. Maintainer would be great. I'd also be happy to invest time in helping to drive prioritization, user engagement, etc. 

I see a lot of value here and am eager to help. 

thanks :)

**Comment by jpreese** [comment]
Any additional thoughts on this @garethr ?

**Comment by garethr** [comment]
Thanks all, I've added the following folks as collaborators on the repo, and set things up to review reviews and PRs into master.

@jpreese @xchapter7x @boranx @Proplex @brendanjryan @Blokje5 

Welcome!
