### ISSUE TITLE
CI not running on pull requests

### ISSUE THREAD

**Issue by brendanjryan** [instrumenta/conftest#49]
I noticed in https://github.com/instrumenta/conftest/pull/48 that CI is not running on pull requests - although it is configured to run on `master`. 

Is this intentional? If not i'd be more than happy to get this integrated on every build!

**Comment by garethr** [comment]
Not intentional, looks like in Circle needed some configuration. I think I've just done that now, so the next PR _should_ trigger the build. That _might_ fail, due to missing environment variables. I'll add some logic to fix that if it does. Thanks for flagging.
