### ISSUE TITLE
Cross-Document support

### ISSUE THREAD

**Issue by bmhatfield** [instrumenta/conftest#5]
Hi! We've started using `conftest` for evaluating our K8S YAML files last week, and it's been a nice way to encode certain conventions we expect our configurations to follow.

One thing that we immediately noticed we wanted but was not possible was to be able to verify fields across documents. For example, a GCE Ingress's service port needs to align with the backing ports in the service/deployment. Or, a deployment that pulls in values from a configmap needs to match the metadata names.

I took a quick skim of the code, and in general, it appears that it would require restructuring a bit to support this (the `input` object may need to be more akin to a map or an array), but doing so would unlock some serious configuration checking super powers.

Thanks!
Brian

**Comment by Proplex** [comment]
We've opened a PR (#39) to implement this :)

**Comment by garethr** [comment]
#73 solves for this use case. It will be available in the next release.
