### ISSUE TITLE
Support parsing the stream which comes from stdin

### ISSUE THREAD

**Issue by boranx** [instrumenta/conftest#69]
To expand the usage of conftest with stdin or unknown file extensions, we need a flag for allowing injection of requested parser type. 
After this feature enabled, we will support the commands below: 

```
cat examples/ini/grafana.ini | ./conftest test -p examples/ini/policy/ --flag=ini -
./conftest test -p examples/some/policy/ --flag=toml  examples/some/unknown.xyz
```

**Comment by garethr** [comment]
+1 on the idea. 

Thinking about the name of the flag, a few options:

* `--parser`
* `--input`, `-i`

**Comment by boranx** [comment]
`--input` SGTM,
making a PR about this.
