### ISSUE TITLE
Push fails with local docker registry

### ISSUE THREAD

**Issue by Blokje5** [instrumenta/conftest#71]
Reproduction steps:
1. Start a local docker registry:
```
docker run -it --rm -p 5000:5000 registry
```

2. push a set of policies with Conftest (version 0.11)
```
conftest push localhost:5000/policies:latest
```
results:
```bash
conftest push localhost:5000/policies:latest
time="2019-08-10T14:19:31Z" level=fatal msg="failed to do request: Head http://localhost:5000/v2/policies/blobs/sha256:086ee78899cc6be63d638028055085630d199198424063098fee3c47383928e4: dial tcp 127.0.0.1:5000: connect: connection refused"
```

With ORAS it does succeed:

```bash
oras push localhost:5000/policies:latest ./policy

Uploading e05080fb451c policy
Pushed localhost:5000/policies:latest
Digest: sha256:28d7f27c0158b6df69ce40176ba9da081c6c49be9c450324e06e80d5bf3251c8
```

```bash
oras pull localhost:5000/policies:latest  --output ./tmp

Downloaded e05080fb451c policy
Pulled localhost:5000/policies:latest
Digest: sha256:28d7f27c0158b6df69ce40176ba9da081c6c49be9c450324e06e80d5bf3251c8
```

**Comment by jpreese** [comment]
Thanks for the report, @Blokje5 

Unfortunately I'm not able to reproduce this at the moment. Could you provide a little more detail about your environment and the context in which you're running the command?

I am on Windows 10, conftest v0.11.0, and ran:
`conftest push localhost:5000/policies:latest policy`

Inside of the `examples/kubernetes` folder in the conftest repository

**Comment by jpreese** [comment]
Were you still running into problems with this @Blokje5 ?

**Comment by Blokje5** [comment]
@jpreese I indeed still encounter the same issue. I did find the what is causing the problem though:

Locally I have conftest aliased to the following:

```bash
docker run --rm -v $(pwd):/project instrumenta/conftest
```

Which I completely forgot about. So when running the conftest I am actually executing:

```bash
docker run --rm -v $(pwd):/project instrumenta/conftest push localhost:5000/policies:latest policy
```

Running from the binary directly yields no errors. So the issue is only with the docker image.

On a side note what I did notice was that it was using https in one of the calls, I have no clue why though:

![image](https://user-images.githubusercontent.com/26072918/63112317-33fe2400-bf90-11e9-9665-c371363074b6.png)

It seems it randomly switched between http and https. (look at the last error message)

**Comment by jpreese** [comment]
@Blokje5, because you're running conftest inside of a docker container, it's on a different network than your oci registry container.

i.e. You have two docker containers running. One is serving the OCI registry at localhost:5000 and the other is running conftest inside of it. When referencing localhost:5000 from inside the conftest container, you're effectively trying to connect to the container thats running conftest.

Try adding `--network="host"` to your docker run command so that your container has access to the host's network.

```
docker run --network="host" --rm -v //$(pwd):/project instrumenta/conftest push localhost:5000/policies:latest policy
```

**Comment by Blokje5** [comment]
Yep that works indeed. I will close this issue.
