### ISSUE TITLE
Create a Tekton Task for Conftest

### ISSUE THREAD

**Issue by garethr** [instrumenta/conftest#75]
Just tracking here for visibility, and probably for linking into the documentation. See the PR https://github.com/tektoncd/catalog/pull/60 for the Task itself.

**Comment by garethr** [comment]
This is now merged and available in the catalog https://github.com/tektoncd/catalog/tree/master/conftest

**Comment by soharaki** [comment]
Fix the url link: Now(2020/11/22) available in the catalog https://github.com/tektoncd/catalog/tree/master/task/conftest
