### ISSUE TITLE
New feature request: Extend deny rule name to a list of (deny|violation)

### ISSUE THREAD

**Issue by dolv** [instrumenta/conftest#82]
Recently open policy agent [gatekeeper](https://github.com/open-policy-agent/gatekeeper) has implemented changes in rego code. Now they use `violation` instead of `deny`. We use conftest to verify our PRs before merge. That simple change  has caused the conftest to skip all the checks which worked before.

We kindly ask you to extend deny rule name to a list of (deny|rule|violation).

here you have the patch. 
```
commit cf0c59d92802f5b53bdabc452295b296baef59b8
Author: Oleksandr DUDCHENKO <oleksandr.dudchenko@syncier.com>
Date:   Fri Sep 6 17:21:30 2019 +0300

    extended list for possible deny rule names

diff --git a/pkg/commands/test/test.go b/pkg/commands/test/test.go
index f5ed225..acf9d0d 100644
--- a/pkg/commands/test/test.go
+++ b/pkg/commands/test/test.go
@@ -26,7 +26,7 @@ import (
 )
 
 var (
-	denyQ = regexp.MustCompile("^deny(_[a-zA-Z]+)*$")
+	denyQ = regexp.MustCompile("^(deny|rule|violation)(_[a-zA-Z]+)*$")
 	warnQ = regexp.MustCompile("^warn(_[a-zA-Z]+)*$")
 )
```

**Comment by garethr** [comment]
Thanks, I'd just spotted that as well and was planning on investigating when I had a moment. Happy to apply that patch (and update a few tests) when I get a moment, of if you want to submit a pull request I can merge? Either way will get this into the next release asap.

I'd love to hear more about your use of Conftest with Gatekeeper as well, maybe in the #conftest Slack channel on the Open Policy Agent Slack? I'm starting to do some bits there as well, and wondering about closer integration. I'd love to know more about your workflow going from Rego to the Gatekeeper templates.

**Comment by garethr** [comment]
Resolved in https://github.com/instrumenta/conftest/commit/d3a1f7621c8607178f6def205ef3f6619957fc49. Thanks for the patch.
