### ISSUE TITLE
Add support for "table" output

### ISSUE THREAD

**Issue by lucperkins** [instrumenta/conftest#86]
I'm a big fan of OPA's "table" output largely due to its readability, which you can see at work in [this blog post](https://blog.openpolicyagent.org/policy-driven-continuous-integration-with-open-policy-agent-b98a8748e536) that I wrote. It'd be nice to add that to the supported output options for Conftest.

The implementation seems pretty trivial so I'll attempt it myself.

**Comment by KeisukeYamashita** [comment]
@lucperkins  I submitted a PR for this issue. This pr https://github.com/instrumenta/conftest/pull/182 will solve this.

**Comment by boranx** [comment]
Closing this as we support now.
Thanks, everyone!
