### ISSUE TITLE
Discussion/Feature: Print out structured data from unstructured inputs

### ISSUE THREAD

**Issue by boranx** [instrumenta/conftest#89]
As a Conftest user, I want to know that how the inputs transformed into structured data. This feature especially needed for when we are writing tests against `Dockerfile`, `hcl2`, or `ini` like files, that needs to be parsed.

The JSON output for the parsing process would be nice, in order to understand exactly how the files are transformed and how we can write tests against them:
For instance, to understand which one is correct, `input.x.y["z.t"] = foo` or `input["x"].y["z.t"] = foo`, I have to take a look at the parsers.

I think this can be achieved with a flag like `--reveal-structure` but other suggested ideas are welcomed. btw, I'm not sure if this feature is needed for the users, so let's discuss it!

Any thoughts?

**Comment by Blokje5** [comment]
I like the idea. I indeed often encountered the need to debug conftest in order to determine the internal representation of certain parsed objects. It is easy to reason about for JSON and Yaml, but indeed for things like `Dockerfiles` it is hard to reason about.

**Comment by garethr** [comment]
I like the sound of this, I've run into the same with some of the more interesting input formats.

I think this sounds more like a subcommand than a flag to me? Most of the flags for `test` don't apply, and it's not related to the policy folder at all. A few initial thoughts:

* `conftest reveal`
* `conftest parse`

Slight preference maybe for the later, but open to other suggestions as well.

**Comment by boranx** [comment]
I liked the different subcommand idea and: `conftest parse`. 

Then usage will be like this,
`conftest parse <file>`
`conftest parse <file> -i <option>`

I'm going to start to work on this PR, If you have more ideas, may write to me.
