### ISSUE TITLE
Request: Cut a new release

### ISSUE THREAD

**Issue by kmcquade** [instrumenta/conftest#93]
Hoping that we can get a new release cut soon. Particularly interested in using the feature built in by @Blokje5 in PR #83 . 

@garethr ping :)

**Comment by jpreese** [comment]
If you're really hurting, it should be possible to get your own binary using `go get`

It's not ideal, but may be able to get you over the hump if you're looking to use a later version until gareth can get around to cutting a new release.

**Comment by kmcquade** [comment]
Yep I'm doing that for my development now  :) but I want my users to be able to use the features in the new branch I'm working on for when the new version of conftest is released.

**Comment by garethr** [comment]
Thanks for the interest, v0.13.0 is up now.
