### ISSUE TITLE
Feature request: a one-liner story for remote policy

### ISSUE THREAD

**Issue by nicolasbernard** [instrumenta/conftest#98]
Hi,

All moderns CI tools seems to take the "modular path" where each job step is an OCI image and an overrided entrypoint to customize the command.

Personally I like it and I think Conftest, which as a lot of CI use-cases, make it difficult for remote policies.

Today you have to setup a 2 steps job:
- `conftest pull instrumenta.azurecr.io/test` then `conftest test ...`
- `echo "[[policies]]..." > conftest.toml` then `conftest test --update ...`
- `oras pull bundle.bar/opa/instrumenta/kubernetes:latest -a` then `conftest test -p kubernetes.rego ...`

I haven't UX suggestion atm but I think a one-liner like `conftest test -p oci://bundle.bar/opa/instrumenta/kubernetes:latest ...` could be a great feature

**Comment by mauilion** [comment]
+1 on this one. I was just trying to use deprek8 from `git.io/deprek8` and found that `-p https://git.io/deprek8` don't do it :)

**Comment by Blokje5** [comment]
I like the idea. @mauilion also has a good point. We should probably support more then just OCI registries to fetch data. https would be great. S3 would be nice as well. Maybe even git repositories. I'll log that in a seperate issue though. But the move to using URLs would also be a good opportunity to think about other methods of fetching policies.

**Comment by Blokje5** [comment]
I'll pick this up together with support for HTTPS as the two work well together. If we support HTTPS we need a way to differentiate between OCI and HTTPS, and using URLs is a good way to solve it.

**Comment by Blokje5** [comment]
#107 Closes this. The `--update` flag of the test command now allows you to specify a remote `oci://` (among others, such as `git://` and `http://`) to pull policies in the test command.
